# SITE CONFIGURATION
baseurl: ""
url: "http://neway6655.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Neway
  avatar: neway_avatar.png
  gravatar: 0b46f26b2a5ac0f3b0e52d355d76a3c1
  description: "Neway's blog."
  
  # Header and footer text
  header_text: >     
   Don't find fault. Find a remedy. -- Henry Ford
  footer_text: >
   Copyright 2015
  
  # Icons
  rss: true
  email_address: neway.liu1985@gmail.com
  behance:
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  github: "Neway6655"
  google_plus: 
  instagram: 
  linkedin:  "http://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile"
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:
  steam: 
  tumblr: 
  twitter:
  wordpress: 
  youtube: 
  
  # Scripts
  google_analytics: # tracking id, e.g. "UA-000000-01"
  disqus_shortname:
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "neway.liu1985@gmail.com"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"
  
  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
  
encoding: UTF-8