# Setup
title:        Neway's Backyard About Technology
tagline:      Don't find fault. Find a remedy. -- Henry Ford
baseurl:      ""
paginate:     5
locale:       "en"

# About/contact
author:
  name:       Neway
  url:        https://neway6655.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
